plugins {
    id "com.android.application"
}

android {
    namespace "com.jjabs.videotogif"
    compileSdk 35

    defaultConfig {
        applicationId "com.jjabs.videotogif"
        minSdk 28
        targetSdk 34
        versionCode 10
        versionName "1.9"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}
